### ISSUE TITLE
bug: Allow pull down to refresh on mobile

### ISSUE THREAD

**Issue by Kio-td** [transfem-org/Sharkey#27]
## Summary
either as a toggle, or as a default action, pulling to refresh is a fast and effective way to refresh the page, if anything goes wrong.

**Comment by Mar0xy** [comment]
I wonder what happens if this line gets removed https://github.com/transfem-org/Sharkey/blob/95572749e6f84dbe0ec8bea766b11f9852053137/packages/frontend/src/ui/universal.vue#L243 as this line is the one that disables the reload by pulling down but I assume it would also be there for a reason

**Comment by Insert5StarName** [comment]
remove it lets test what happens

**Comment by CutestNekoAqua** [comment]
It should be the default to allow pulling down!

**Comment by codingneko** [comment]
Any updates on this? It'd be pretty poggers to have...

**Comment by Mar0xy** [comment]
It got a fix in upstream and will most likely be released next release

**Comment by codingneko** [comment]
Amazing news, thanks @Mar0xy <3

**Comment by codingneko** [comment]
Heyy, so I just wanted to let you know this implementation isn't very good, it only really works on the homepage, which isn't very useful because it already refreshes by default with websockets... 

I would prefer this to be implemented with the default browser pull down to refresh because it would allow for refresh of any page. 

There are lots of places where sharkey / misskey does not refresh correctly via webhooks, like when you're the one posting a reply from the post details view or when posting normally from the user profile view. The notification page also doesn't refresh correctly via webhooks, only the notification widget does.

In order to avoid implementing a pull down to refresh for each specific component, and fixing webhooks everywhere, I think it's MUCH easier to just let the user pull down...

**Comment by Mar0xy** [comment]
> I would prefer this to be implemented with the default browser pull down to refresh

This is not possible with how the client is made which is why misskey went with a custom option if you need it on every page then add the component on every page but here we are currently waiting to see what misskey themself does before doing anything else with the pull to refresh.

**Comment by codingneko** [comment]
Uh that sucks... Alright, thanks for trying at least >~<
And for the explaination!
