### ISSUE TITLE
Group reaction emojis by emoji hash

### ISSUE THREAD

**Issue by codingneko** [transfem-org/Sharkey#29]
# Summary
When reacting from different instances, custom emoji reactions that are the same have separate counts depending on which instance they were sent from. 

![image](https://github.com/transfem-org/Sharkey/assets/11065075/56ea4269-26ac-468d-b337-9140772cdfca)

# Proposed implementation idea
It would be awesome to have these grouped by image hash. Also, when a custom emoji reaction from a remote instance that is also present on the local instance is clicked, nothing happens. I propose checking for the image hash on the local instance, and if one with the same hash is present, send that.

**Comment by Mar0xy** [comment]
This was discussed in the discord already and was advised against by mulitple people.

"I actually think this would be pretty easy to implement, and should work on any instance. I'd need to see a formal JSON-LD context to be sure. But just because you can do it doesn't mean that you should!"

"It's just a limitation of activitypub as far as I can tell, I'm sure you could commit some crimes to make that work but it would only work on instances running the same software as yours, like a flag that merges emojis of the same name together when they're shown as a react
(this is a terrible idea and I wouldn't ever recommend implementing something like that)
"

**Comment by codingneko** [comment]
Oh... ok then :< thanks for taking the time to read and reply anyway 😸
