### ISSUE TITLE
URLs containing apostrophes are not displayed correctly

### ISSUE THREAD

**Issue by 1bcb** [transfem-org/Sharkey#50]
## 💡 Summary

If you post a URL containing an apostrophe, Sharkey interprets everything before the first apostrophe as the full URL, and everything after the apostrophe as not part of the URL.  This leads to a broken link.

## 🥰 Expected Behavior

A URL I put in a post should show up as a hyperlink.

## 🤬 Actual Behavior

Only part of the URL is hyperlinked, making the link point to the wrong place.

## 📝 Steps to Reproduce

1. Find a web page with a URL containing an apostrophe, such as `https://pandorastale.miraheze.org/wiki/Pandora's_Tale_Wiki:Moving_to_a_Custom_Domain`
2. Copy and paste the URL from step (1) into a Sharkey post.

## 📌 Environment

Reproduced on :
estrogen.plus running Sharkey 2023.9.1.beta3
transfem.social running Sharkey 2023.9.1.beta3

### 💻 Frontend
* Model and OS of the device(s):
  Linux Mint 21.2 Cinnamon desktop
* Browser:
  Firefox 118.0.1 Flatpak
* Server URL:
  estrogen.plus and
  transfem.social
* Sharkey 2023.9.1.beta3

**Comment by Mar0xy** [comment]
This is not just specific to Sharkey as this happens on every Fediverse software due to the way the markdown systems work as this URL in itself is not proper the actual proper URL which would make it function on every software would be:

`https://pandorastale.miraheze.org/wiki/Pandora%27s_Tale_Wiki:Moving_to_a_Custom_Domain`

See here to see it function fully: https://dev.joinsharkey.org/notes/9kea5wllmbqd0001

Here you can also see it happen on Mastodon: https://social.lol/@pandorastalewiki@estrogen.plus/111151537494469744

There is also no clear way to know when a URL stops or ends which is why the URL also needs to be always in one line and seperate by spaces from other text.
